version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        build: .
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        links:
            - mysql:mysqlhost
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306 
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=users-training